plugins {
	id 'net.neoforged.moddev' version '2.0.141'
	id 'maven-publish'
}

version = project.mod_version
group = project.mod_group_id

base {
	archivesName = project.mod_id
}

tasks.withType(AbstractArchiveTask).configureEach {
	archiveVersion = "${project.mod_version}-${project.minecraft_version}-neo"
}

repositories {
	mavenCentral()
	maven {
		name = "NeoForged"
		url = "https://maven.neoforged.net/releases/"
	}
	maven {
		name = "Minecraft Libraries"
		url = "https://libraries.minecraft.net/"
	}
	maven {
		name = "RedlanceMinecraft"
		url = "https://repo.redlance.org/public"
	}
}

neoForge {
	version = project.neo_version

	runs {
		client {
			client()
			systemProperty "neoforge.enabledGameTestNamespaces", project.mod_id
		}
		server {
			server()
			systemProperty "neoforge.enabledGameTestNamespaces", project.mod_id
		}
	}

	mods {
		"${project.mod_id}" {
			sourceSet sourceSets.main
		}
	}
}

dependencies {
	implementation "net.neoforged:neoforge:${project.neo_version}"
	implementation("com.zigythebird.playeranim:PlayerAnimationLibNeo:${project.pal_version}") {
		exclude group: "com.google.code.gson"
		exclude group: "org.slf4j"
		exclude group: "it.unimi.dsi", module: "fastutil"
		exclude group: "io.netty"
		exclude group: "org.joml"
		exclude group: "org.jetbrains", module: "annotations"
	}
}

processResources {
	inputs.property "version", project.version

	filesMatching("META-INF/neoforge.mods.toml") {
		expand(
				minecraft_version: project.minecraft_version,
				mod_group_id: project.mod_group_id,
				mod_id: project.mod_id,
				mod_license: project.mod_license,
				mod_name: project.mod_name,
				mod_version: project.mod_version,
				neo_version: project.neo_version,
				pal_version: project.pal_version
		)
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()

	toolchain.languageVersion = JavaLanguageVersion.of(25)
}

jar {
	inputs.property "projectName", project.mod_id

	from("LICENSE") {
		rename { "${it}_${project.mod_id}" }
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}
