# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, so keep it off.
org.gradle.configuration-cache=false

# NeoForge Properties
# check these on https://docs.neoforged.net/
minecraft_version=1.21.1
neo_version=21.1.235

# Mod Properties
mod_version=1.0.0
mod_id=takeaseat
mod_name=Take a Seat
mod_license=All-Rights-Reserved
mod_group_id=com.takeaseat

# Dependencies
# Player Animation Library (https://repo.redlance.org/public)
pal_version=1.1.4+mc.1.21.1
